# Generated by Django 4.2.27 on 2025-12-08 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "membership_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="会员过期时间"
                    ),
                ),
                (
                    "membership_level",
                    models.CharField(
                        choices=[
                            ("free", "无会员"),
                            ("day", "日会员"),
                            ("week", "周会员"),
                            ("month", "月会员"),
                            ("year", "年会员"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="当前会员类型",
                    ),
                ),
                (
                    "membership_scope_city",
                    models.TextField(
                        blank=True, default="[]", verbose_name="查看城市权限"
                    ),
                ),
                (
                    "membership_scope_item",
                    models.TextField(
                        blank=True, default="[]", verbose_name="查看指标权限"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
