# Generated by Django 4.2.27 on 2025-12-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="membership_level",
            field=models.CharField(
                choices=[
                    ("free", "无会员"),
                    ("day", "日会员"),
                    ("week", "周会员"),
                    ("month", "月会员"),
                    ("year", "年会员"),
                    ("admin", "管理员"),
                ],
                default="free",
                max_length=20,
                verbose_name="当前会员类型",
            ),
        ),
    ]
