








INDIMAP = {
    "地市名称": "city_name",
    "亿元GDP生产安全事故死亡率": "production_safety_accidents_death_per_100million_gdp_rate",
    "十万人工矿商贸从业人员事故死亡率": "industrial_safety_accidents_death_per_100thousand_staff_rate",
    "工矿商贸死亡人数": "industrial_safety_accidents_death_num",
    "火灾死亡人数": "fire_death_num",
    "接待群众来信来访人次": "receive_public_visit_num",
    "刑事案件立案件数": "file_criminal_case_num",
    "刑事案件破案件数": "solve_criminal_case_num",
    "成功调处各类矛盾纠纷数": "solve_conflict_dispute_num",
    "生产安全事故死亡人数": "production_safety_accidents_death_num",
    "受理各类法律援助案件的数量": "legal_aid_case_num",
    "调处各类矛盾纠纷件数": "mediation_conflict_dispute_num",
    "万人刑事案件发案件数": "criminal_case_per_10thousand",
    "万人刑事案件破案件数": "solve_criminal_case_per_10thousand",
    "财政总收入": "total_revenue",
    "财政总收入增长率": "incre_rate_total_revenue",
    "财政总支出": "total_expend",
    "公共安全支出": "public_safety_budget_expend",
    "环保支出": "environment_budget_expend",
    "教育支出": "education_budget_expend",
    "科学技术支出": "tech_budget_expend",
    "社会保障和就业支出": "social_security_budget_expend",
    "文化体育传媒支出": "culture_budget_expend",
    "医疗卫生支出": "medical_budget_expend",
    "一般公共预算收入": "public_budget_revenue",
    "一般公共预算支出": "public_budget_expend",
    "一般公共服务支出": "public_service_budget_expend",
    "固定宽带互联网用户数": "broadband_user_num",
    "每万人拥有公共（电）汽车数量": "bus_per_10thousand",
    "农村自来水覆盖率（农村安全饮水覆盖率）": "rural_tap_water_coverage_rate",
    "人均城市道路面积": "avg_city_road_area",
    "有线电视入户率": "cable_tv_household_rate",
    "有线电视用户数": "cable_tv_user_num",
    "自来水受益村数": "tap_water_village_num",
    "村委会个数": "government_village_num",
    "R&D经费": "rd_funds",
    "R&D经费与GDP之比": "rd_funds_gdp_ratio",
    "专利授权量": "grant_patent_num",
    "专任教师数": "full_time_teacher_num",
    "高中阶段教育在校生人数": "high_school_student_num",
    "高中阶段毛入学率": "high_school_enrollment_rate",
    "普通小学在校生人数": "primary_school_student_num",
    "普通中学在校生人数": "middle_school_student_num",
    "普通小学专任教师数": "primary_school_teacher_num",
    "普通中学专任教师数": "middle_school_teacher_num",
    "第三产业增加值占GDP（增量）比重": "incre_rate_third_industry_in_gdp",
    "第二产业增加值占GDP（增量）比重": "incre_rate_second_industry_in_gdp",
    "高新技术企业产值": "output_value_high_tech_company",
    "高新技术企业增加值": "incre_value_high_tech_company",
    "技术合同成交额": "value_tech_contract",
    "技术合同成交额增长率": "incre_rate_tech_contract",
    "每万人发明专利拥有量": "patent_per_10thousand",
    "年末实有内资企业": "domestic_company_year_end",
    "年末实有企业数": "company_num_year_end",
    "年末实有农民专业合作社": "farmer_cooperative_num_year_end",
    "年末实有外资企业": "foreign_company_year_end",
    "年末实有个体工商户": "individual_company_year_end",
    "有效发明专利量": "patent_num",
    "国有资产保值增值率": "maintain_incre_state_owned_assets",
    "GDP": "gdp",
    "GDP增长率": "incre_rate_gdp",
    "规模以上工业企业产值增加值增长率": "incre_rate_above_size_company_added_value",
    "规模以上工业企业增加值": "above_size_company_added_value",
    "固定资产投资总额": "fixed_assets_investment_total",
    "固定资产投资总额增长率": "incre_rate_fixed_assets_investment_total",
    "进出口总额": "import_export_total",
    "进出口总额增长率": "incre_rate_import_export_total",
    "人均GDP": "avg_gdp",
    "全社会消费品零售总额": "retail_sales_consumer_goods",
    "全社会消费品零售总额增长率": "incre_rate_retail_sales_consumer_goods",
    "实际利用外资金额": "actual_amount_foreign_capital",
    "实际利用外资金额增长率": "incre_rate_actual_amount_foreign_capital",
    "城镇居民人均可支配收入": "city_avg_income",
    "城镇居民人均可支配收入增长率": "incre_rate_city_avg_income",
    "城镇居民人均消费支出": "city_avg_consumption_expend",
    "城镇恩格尔系数": "city_engel",
    "城镇食品支出": "city_food_consumption_expend",
    "工业品出厂价格指数PPI": "ppi",
    "居民消费价格指数CPI": "cpi",
    "农村居民人均可支配收入": "country_avg_income",
    "农村居民人均可支配收入增长率": "incre_rate_country_avg_income",
    "农村居民人均消费支出": "country_avg_consumption_expend",
    "农村恩格尔系数": "country_engel",
    "农村食品支出": "country_food_consumption_expend",
    "采矿（掘）业就业人员人数": "mining_work_pop_total",
    "采矿（掘）业在岗职工人数": "mining_work_pop_year_end",
    "城镇登记失业率": "rate_city_unemployed",
    "城镇登记失业人员数": "city_unemployed_person_num",
    "城镇单位职工工资总额": "city_total_salary",
    "城镇就业人数（城镇单位职工总数）": "city_work_pop_total",
    "城镇新增就业人数": "incre_city_employment_num",
    "公共管理、社会保障和社会组织工资总额": "salary_total_public_social",
    "公共管理、社会保障和社会组织在岗职工人数": "work_pop_public_social",
    "机关单位工资总额": "salary_total_government_agency",
    "机关单位就业人数": "work_pop_government_agency",
    "社会从业人员": "social_employment_pop",
    "制造业就业人员人数": "mfg_work_pop_total",
    "制造业在岗职工人数": "mfg_work_pop_year_end",
    "15-19岁人口数": "pop_15_19",
    "60岁以上老人人口数": "above_60_pop",
    "常住人口": "long_term_pop",
    "城镇化率": "urbanization_rate",
    "出生人口性别比": "birth_pop_gender_rate",
    "户籍人口": "registered_pop",
    "年末总户数": "household_num_year_end",
    "年末总人口": "year_end_pop",
    "人口出生率": "birth_rate",
    "城镇人口": "city_pop",
    "乡村人口": "country_pop",
    "城乡居民基本养老保险人数": "residents_pension_insurance",
    "城乡居民基本医疗保险人数": "residents_medical_insurance",
    "城镇职工基本养老保险人数": "employees_pension_insurance",
    "城镇职工基本医疗保险人数": "employees_medical_insurance",
    "城镇最低生活保障人数": "city_minimum_living_standard_pop",
    "农村最低生活保障人数": "country_minimum_living_standard_pop",
    "年末实有社会组织登记数量": "social_org_num_year_end",
    "新建保障性住房套数": "build_affordable_house_unit",
    "养老机构床位数": "pension_bed_num",
    "PM10": "pm10",
    "PM2.5": "pm25",
    "城市空气质量指数": "city_air_quality",
    "城市区域环境噪音指数": "city_noise_index",
    "二氧化硫排放总量": "so2_total",
    "工业二氧化硫排放量": "so2_industry",
    "工业废水排放总量": "industry_wastewater_amount",
    "工业固体废弃物综合利用率": "industrial_solid_waste_utilization_rate",
    "森林覆盖率": "forest_cover_rate",
    "生活垃圾无害化处理率": "household_waste_treatment_rate",
    "水土流失治理面积": "soil_erosion_control_area",
    "城镇生活污水处理率": "city_sewage_treatment_rate",
    "能源消费总量": "total_energy_consumption",
    "万元GDP综合能源消耗": "energy_consumption_per_10thousand_gdp",
    "万元GDP综合能源消耗降低率": "decre_rate_energy_consumption_per_10thousand_gdp",
    "园林绿地面积": "green_area",
    "查办各类经济违法案件的数量": "economic_illegal_case_num",
    "查办违法广告的件数": "illegal_cases_ad_num",
    "查办商标侵权案件的件数": "illegal_cases_trademark_num",
    "查处农资违法案件的数量": "illegal_cases_agricultural_num",
    "查出不正当竞争案件数": "unfair_comp_case_num",
    "工业产品质量抽样合格率": "industry_qualified_rate",
    "食品质量抽样检测合格率": "food_qualified_rate",
    "受理消费者投诉案件数": "consumer_complaint_case_num",
    "受理消费者维权案件数": "consumer_rights_protection_case_num",
    "消费者维权案件办理率": "consumer_rights_protection_process_rate",
    "药品安全抽样合格率": "medicine_qualified_rate",
    "博物馆": "museum_num",
    "公共图书馆": "library_num",
    "体育场馆": "sport_center_num",
    "文化馆、群众艺术馆": "cultural_center_num",
    "艺术表演团体": "art_team_num",
    "辖区面积": "area",
    "县个数": "county_num",
    "区个数": "district_num",
    "市个数": "city_num",
    "被依法追究责任的领导干部人数": "hold_accountable_leader_num",
    "渎职侵权人数": "dereliction_duty_num",
    "贪污贿赂人数": "corruption_bribery_num",
    "职务犯罪人数": "duty_crime_num",
    "立案查处违法违纪案件数": "file_illegal_case_num",
    "行政案件数": "admin_cases_num",
    "行政复议案件办结率": "admin_recon_cases_completion_rate",
    "行政复议案件申请量": "admin_recon_cases_apply_num",
    "主动公开政府信息件数": "active_disclose_government_information_num",
    "主动公开政府信息增长率": "incre_rate_active_disclose_government_information",
    "依申请公开政府信息件数": "apply_disclose_government_information_num",
    "依申请公开政府信息增长率": "incre_rate_apply_disclose_government_information",
    "因公开问题申请行政复议的数量": "public_issues_disclose_government_information_num",
    "卫生技术人员数量": "medical_staff_num",
    "医疗机构病床数": "medical_bed_num",
    "地市名称": "city_name",
    "市数量": "city_num",
    "市": "city_num",
    "区数量": "district_num",
    "区": "district_num",
    "县数量": "county_num",
    "县": "county_num",
    "常住人口数": "long_term_pop",
    "城镇人口数": "city_pop",
    "乡村人口数": "country_pop",
    "户籍人口数": "registered_pop",
    "60岁以上人口数": "above_60_pop",
    "年末个体工商户数量": "individual_company_year_end",
    "年末内资企业数": "domestic_company_year_end",
    "年末外资企业数": "foreign_company_year_end",
    "年末私营企业数": "private_company_year_end",
    "技术合同成交额（交易额）": "value_tech_contract",
    "技术合同成交额（交易额）增长率": "incre_rate_tech_contract",
    "有效发明专利量（发明专利有效量）": "patent_num",
    "专利授权数量": "grant_patent_num",
    "普通小学在校学生数": "primary_school_student_num",
    "普通中学在校学生数": "middle_school_student_num",
    "高中学在校学生数": "high_school_student_num",
    "采矿（掘)业就业人员人数": "mining_work_pop_total",
    "采矿（掘)业在岗职工人数": "mining_work_pop_year_end",
    "城镇就业人数（城镇单位职工总数（城镇单位就业人数+城镇私营就业人数））": "city_work_pop_total",
    "农民居民人均可支配收入": "country_avg_income",
    "农民居民人均可纯收入": "country_avg_income",
    "农民居民人均可支配收入增长率": "incre_rate_country_avg_income",
    "农民居民人均可纯收入增长率": "incre_rate_country_avg_income",
    "能源消耗总量": "total_energy_consumption",
    "城市区域环境噪音指数（市区区域环境噪音平均等效声级值）": "city_noise_index",
    "规模以上工业企业增加值增长率": "incre_rate_above_size_company_added_value",
}

INDIMAP_UNIT = {
    "above_60_pop": {"unit": "万人", "name_zh": "60岁以上老人人口数"},
    "above_size_company_added_value": {"unit": "亿元", "name_zh": "规模以上工业企业增加值"},
    "active_disclose_government_information_num": {"unit": "件", "name_zh": "主动公开政府信息件数"},
    "actual_amount_foreign_capital": {"unit": "万美元", "name_zh": "实际利用外资金额"},
    "admin_cases_num": {"unit": "件", "name_zh": "行政案件数"},
    "admin_recon_cases_apply_num": {"unit": "件", "name_zh": "行政复议案件申请量"},
    "admin_recon_cases_completion_rate": {"unit": "%", "name_zh": "行政复议案件办结率"},
    "apply_disclose_government_information_num": {"unit": "件", "name_zh": "依申请公开政府信息件数"},
    "area": {"unit": "平方公里", "name_zh": "辖区面积"},
    "art_team_num": {"unit": "个", "name_zh": "艺术表演团体"},
    "avg_city_road_area": {"unit": "平方米/人", "name_zh": "人均城市道路面积"},
    "avg_gdp": {"unit": "元", "name_zh": "人均GDP"},
    "birth_pop_gender_rate": {"unit": "%", "name_zh": "出生人口性别比"},
    "birth_rate": {"unit": "‰", "name_zh": "人口出生率"},
    "broadband_user_num": {"unit": "万户", "name_zh": "固定宽带互联网用户数"},
    "build_affordable_house_unit": {"unit": "套", "name_zh": "新建保障性住房套数"},
    "bus_per_10thousand": {"unit": "辆/万人", "name_zh": "每万人拥有公共（电）汽车数量"},
    "cable_tv_household_rate": {"unit": "%", "name_zh": "有线电视入户率"},
    "cable_tv_user_num": {"unit": "万户", "name_zh": "有线电视用户数"},
    "city_air_quality": {"unit": "%", "name_zh": "城市空气质量指数"},
    "city_avg_consumption_expend": {"unit": "元", "name_zh": "城镇居民人均消费支出"},
    "city_avg_income": {"unit": "元", "name_zh": "城镇居民人均可支配收入"},
    "city_engel": {"unit": "%", "name_zh": "城镇恩格尔系数"},
    "city_food_consumption_expend": {"unit": "元", "name_zh": "城镇食品支出"},
    "city_minimum_living_standard_pop": {"unit": "人", "name_zh": "城镇最低生活保障人数"},
    "city_name": {"unit": "", "name_zh": "地市名称"},
    "city_noise_index": {"unit": "分贝", "name_zh": "城市区域环境噪音指数"},
    "city_num": {"unit": "个", "name_zh": "市个数"},
    "city_pop": {"unit": "万人", "name_zh": "城镇人口"},
    "city_sewage_treatment_rate": {"unit": "%", "name_zh": "城镇生活污水处理率"},
    "city_total_salary": {"unit": "万元", "name_zh": "城镇单位职工工资总额"},
    "city_unemployed_person_num": {"unit": "人", "name_zh": "城镇登记失业人员数"},
    "city_work_pop_total": {"unit": "万人", "name_zh": "城镇就业人数（城镇单位职工总数）"},
    "company_num_year_end": {"unit": "户（个）", "name_zh": "年末实有企业数"},
    "consumer_complaint_case_num": {"unit": "件", "name_zh": "受理消费者投诉案件数"},
    "consumer_rights_protection_case_num": {"unit": "件", "name_zh": "受理消费者维权案件数"},
    "consumer_rights_protection_process_rate": {"unit": "%", "name_zh": "消费者维权案件办理率"},
    "corruption_bribery_num": {"unit": "人", "name_zh": "贪污贿赂人数"},
    "country_avg_consumption_expend": {"unit": "元", "name_zh": "农村居民人均消费支出"},
    "country_avg_income": {"unit": "元", "name_zh": "农村居民人均可支配收入"},
    "country_engel": {"unit": "%", "name_zh": "农村恩格尔系数"},
    "country_food_consumption_expend": {"unit": "元", "name_zh": "农村食品支出"},
    "country_minimum_living_standard_pop": {"unit": "人", "name_zh": "农村最低生活保障人数"},
    "country_pop": {"unit": "万人", "name_zh": "乡村人口"},
    "county_num": {"unit": "个", "name_zh": "县个数"},
    "cpi": {"unit": "%", "name_zh": "居民消费价格指数CPI"},
    "criminal_case_per_10thousand": {"unit": "件/万人", "name_zh": "万人刑事案件发案件数"},
    "cultural_center_num": {"unit": "个", "name_zh": "文化馆、群众艺术馆"},
    "culture_budget_expend": {"unit": "亿元", "name_zh": "文化体育传媒支出"},
    "decre_rate_energy_consumption_per_10thousand_gdp": {"unit": "%", "name_zh": "万元GDP综合能源消耗降低率"},
    "dereliction_duty_num": {"unit": "人", "name_zh": "渎职侵权人数"},
    "district_num": {"unit": "个", "name_zh": "区个数"},
    "domestic_company_year_end": {"unit": "户（个）", "name_zh": "年末实有内资企业"},
    "duty_crime_num": {"unit": "人", "name_zh": "职务犯罪人数"},
    "economic_illegal_case_num": {"unit": "件", "name_zh": "查办各类经济违法案件的数量"},
    "education_budget_expend": {"unit": "亿元", "name_zh": "教育支出"},
    "employees_medical_insurance": {"unit": "万人", "name_zh": "城镇职工基本医疗保险人数"},
    "employees_pension_insurance": {"unit": "万人", "name_zh": "城镇职工基本养老保险人数"},
    "energy_consumption_per_10thousand_gdp": {"unit": "吨标准煤／万元", "name_zh": "万元GDP综合能源消耗"},
    "environment_budget_expend": {"unit": "亿元", "name_zh": "环保支出"},
    "farmer_cooperative_num_year_end": {"unit": "户（个）", "name_zh": "年末实有农民专业合作社"},
    "file_criminal_case_num": {"unit": "件", "name_zh": "刑事案件立案件数"},
    "file_illegal_case_num": {"unit": "件", "name_zh": "立案查处违法违纪案件数"},
    "fire_death_num": {"unit": "人", "name_zh": "火灾死亡人数"},
    "fixed_assets_investment_total": {"unit": "亿元", "name_zh": "固定资产投资总额"},
    "food_qualified_rate": {"unit": "%", "name_zh": "食品质量抽样检测合格率"},
    "foreign_company_year_end": {"unit": "户（个）", "name_zh": "年末实有外资企业"},
    "forest_cover_rate": {"unit": "%", "name_zh": "森林覆盖率"},
    "full_time_teacher_num": {"unit": "人", "name_zh": "专任教师数"},
    "gdp": {"unit": "亿元", "name_zh": "GDP"},
    "government_village_num": {"unit": "个", "name_zh": "村委会个数"},
    "grant_patent_num": {"unit": "件", "name_zh": "专利授权量"},
    "green_area": {"unit": "公顷", "name_zh": "园林绿地面积"},
    "high_school_enrollment_rate": {"unit": "%", "name_zh": "高中阶段毛入学率"},
    "high_school_student_num": {"unit": "万人", "name_zh": "高中阶段教育在校生人数"},
    "hold_accountable_leader_num": {"unit": "人", "name_zh": "被依法追究责任的领导干部人数"},
    "household_num_year_end": {"unit": "万户", "name_zh": "年末总户数"},
    "household_waste_treatment_rate": {"unit": "%", "name_zh": "生活垃圾无害化处理率"},
    "illegal_cases_ad_num": {"unit": "件", "name_zh": "查办违法广告的件数"},
    "illegal_cases_agricultural_num": {"unit": "件", "name_zh": "查处农资违法案件的数量"},
    "illegal_cases_trademark_num": {"unit": "件", "name_zh": "查办商标侵权案件的件数"},
    "import_export_total": {"unit": "万美元", "name_zh": "进出口总额"},
    "incre_city_employment_num": {"unit": "万人", "name_zh": "城镇新增就业人数"},
    "incre_rate_above_size_company_added_value": {"unit": "%", "name_zh": "规模以上工业企业产值增加值增长率"},
    "incre_rate_active_disclose_government_information": {"unit": "%", "name_zh": "主动公开政府信息增长率"},
    "incre_rate_actual_amount_foreign_capital": {"unit": "%", "name_zh": "实际利用外资金额增长率"},
    "incre_rate_apply_disclose_government_information": {"unit": "%", "name_zh": "依申请公开政府信息增长率"},
    "incre_rate_city_avg_income": {"unit": "%", "name_zh": "城镇居民人均可支配收入增长率"},
    "incre_rate_country_avg_income": {"unit": "%", "name_zh": "农村居民人均可支配收入增长率"},
    "incre_rate_fixed_assets_investment_total": {"unit": "%", "name_zh": "固定资产投资总额增长率"},
    "incre_rate_gdp": {"unit": "%", "name_zh": "GDP增长率"},
    "incre_rate_import_export_total": {"unit": "%", "name_zh": "进出口总额增长率"},
    "incre_rate_retail_sales_consumer_goods": {"unit": "%", "name_zh": "全社会消费品零售总额增长率"},
    "incre_rate_second_industry_in_gdp": {"unit": "%", "name_zh": "第二产业增加值占GDP（增量）比重"},
    "incre_rate_tech_contract": {"unit": "%", "name_zh": "技术合同成交额增长率"},
    "incre_rate_third_industry_in_gdp": {"unit": "%", "name_zh": "第三产业增加值占GDP（增量）比重"},
    "incre_rate_total_revenue": {"unit": "%", "name_zh": "财政总收入增长率"},
    "incre_value_high_tech_company": {"unit": "亿元", "name_zh": "高新技术企业增加值"},
    "individual_company_year_end": {"unit": "户（个）", "name_zh": "年末实有个体工商户"},
    "industrial_safety_accidents_death_num": {"unit": "人", "name_zh": "工矿商贸死亡人数"},
    "industrial_safety_accidents_death_per_100thousand_staff_rate": {"unit": "%", "name_zh": "十万人工矿商贸从业人员事故死亡率"},
    "industrial_solid_waste_utilization_rate": {"unit": "%", "name_zh": "工业固体废弃物综合利用率"},
    "industry_qualified_rate": {"unit": "%", "name_zh": "工业产品质量抽样合格率"},
    "industry_wastewater_amount": {"unit": "万吨", "name_zh": "工业废水排放总量"},
    "legal_aid_case_num": {"unit": "件", "name_zh": "受理各类法律援助案件的数量"},
    "library_num": {"unit": "个", "name_zh": "公共图书馆"},
    "long_term_pop": {"unit": "万人", "name_zh": "常住人口"},
    "maintain_incre_state_owned_assets": {"unit": "%", "name_zh": "国有资产保值增值率"},
    "mediation_conflict_dispute_num": {"unit": "件", "name_zh": "调处各类矛盾纠纷件数"},
    "medical_bed_num": {"unit": "张", "name_zh": "医疗机构病床数"},
    "medical_budget_expend": {"unit": "亿元", "name_zh": "医疗卫生支出"},
    "medical_staff_num": {"unit": "人", "name_zh": "卫生技术人员数量"},
    "medicine_qualified_rate": {"unit": "%", "name_zh": "药品安全抽样合格率"},
    "mfg_work_pop_total": {"unit": "万人", "name_zh": "制造业就业人员人数"},
    "mfg_work_pop_year_end": {"unit": "万人", "name_zh": "制造业在岗职工人数"},
    "middle_school_student_num": {"unit": "万人", "name_zh": "普通中学在校生人数"},
    "middle_school_teacher_num": {"unit": "人", "name_zh": "普通中学专任教师数"},
    "mining_work_pop_total": {"unit": "万人", "name_zh": "采矿（掘）业就业人员人数"},
    "mining_work_pop_year_end": {"unit": "万人", "name_zh": "采矿（掘）业在岗职工人数"},
    "museum_num": {"unit": "个", "name_zh": "博物馆"},
    "output_value_high_tech_company": {"unit": "亿元", "name_zh": "高新技术企业产值"},
    "patent_num": {"unit": "件", "name_zh": "有效发明专利量"},
    "patent_per_10thousand": {"unit": "件/万人", "name_zh": "每万人发明专利拥有量"},
    "pension_bed_num": {"unit": "张", "name_zh": "养老机构床位数"},
    "pm10": {"unit": "微克每立方米", "name_zh": "PM10"},
    "pm25": {"unit": "微克每立方米", "name_zh": "PM2.5"},
    "pop_15_19": {"unit": "人", "name_zh": "15-19岁人口数"},
    "ppi": {"unit": "%", "name_zh": "工业品出厂价格指数PPI"},
    "primary_school_student_num": {"unit": "万人", "name_zh": "普通小学在校生人数"},
    "primary_school_teacher_num": {"unit": "人", "name_zh": "普通小学专任教师数"},
    "production_safety_accidents_death_num": {"unit": "人", "name_zh": "生产安全事故死亡人数"},
    "production_safety_accidents_death_per_100million_gdp_rate": {"unit": "%", "name_zh": "亿元GDP生产安全事故死亡率"},
    "public_budget_expend": {"unit": "亿元", "name_zh": "一般公共预算支出"},
    "public_budget_revenue": {"unit": "亿元", "name_zh": "一般公共预算收入"},
    "public_issues_disclose_government_information_num": {"unit": "件", "name_zh": "因公开问题申请行政复议的数量"},
    "public_safety_budget_expend": {"unit": "亿元", "name_zh": "公共安全支出"},
    "public_service_budget_expend": {"unit": "亿元", "name_zh": "一般公共服务支出"},
    "rate_city_unemployed": {"unit": "%", "name_zh": "城镇登记失业率"},
    "rd_funds": {"unit": "亿元", "name_zh": "R&D经费"},
    "rd_funds_gdp_ratio": {"unit": "%", "name_zh": "R&D经费与GDP之比"},
    "receive_public_visit_num": {"unit": "件次", "name_zh": "接待群众来信来访人次"},
    "registered_pop": {"unit": "万人", "name_zh": "户籍人口"},
    "residents_medical_insurance": {"unit": "万人", "name_zh": "城乡居民基本医疗保险人数"},
    "residents_pension_insurance": {"unit": "万人", "name_zh": "城乡居民基本养老保险人数"},
    "retail_sales_consumer_goods": {"unit": "亿元", "name_zh": "全社会消费品零售总额"},
    "rural_tap_water_coverage_rate": {"unit": "%", "name_zh": "农村自来水覆盖率（农村安全饮水覆盖率）"},
    "salary_total_government_agency": {"unit": "万元", "name_zh": "机关单位工资总额"},
    "salary_total_public_social": {"unit": "万元", "name_zh": "公共管理、社会保障和社会组织工资总额"},
    "so2_industry": {"unit": "吨", "name_zh": "工业二氧化硫排放量"},
    "so2_total": {"unit": "吨", "name_zh": "二氧化硫排放总量"},
    "social_employment_pop": {"unit": "万人", "name_zh": "社会从业人员"},
    "social_org_num_year_end": {"unit": "个", "name_zh": "年末实有社会组织登记数量"},
    "social_security_budget_expend": {"unit": "亿元", "name_zh": "社会保障和就业支出"},
    "soil_erosion_control_area": {"unit": "公顷", "name_zh": "水土流失治理面积"},
    "solve_conflict_dispute_num": {"unit": "件", "name_zh": "成功调处各类矛盾纠纷数"},
    "solve_criminal_case_num": {"unit": "件", "name_zh": "刑事案件破案件数"},
    "solve_criminal_case_per_10thousand": {"unit": "件/万人", "name_zh": "万人刑事案件破案件数"},
    "sport_center_num": {"unit": "个", "name_zh": "体育场馆"},
    "tap_water_village_num": {"unit": "个", "name_zh": "自来水受益村数"},
    "tech_budget_expend": {"unit": "亿元", "name_zh": "科学技术支出"},
    "total_energy_consumption": {"unit": "吨标准煤", "name_zh": "能源消费总量"},
    "total_expend": {"unit": "亿元", "name_zh": "财政总支出"},
    "total_revenue": {"unit": "亿元", "name_zh": "财政总收入"},
    "unfair_comp_case_num": {"unit": "个", "name_zh": "查出不正当竞争案件数"},
    "urbanization_rate": {"unit": "%", "name_zh": "城镇化率"},
    "value_tech_contract": {"unit": "亿元", "name_zh": "技术合同成交额"},
    "work_pop_government_agency": {"unit": "人", "name_zh": "机关单位就业人数"},
    "work_pop_public_social": {"unit": "人", "name_zh": "公共管理、社会保障和社会组织在岗职工人数"},
    "year_end_pop": {"unit": "万人", "name_zh": "年末总人口"},
}

AREA_INDIMAP = {
    "常住人口": "long_term_pop",
    "常住人口数": "long_term_pop",
    "户籍人口": "registered_pop",
    "户籍人口数": "registered_pop",
    "GDP": "gdp",
    "人均GDP": "avg_gdp",
    "GDP增长率": "incre_rate_gdp",
    "一般公共预算收入": "public_budget_revenue",
    "一般公共预算收入增长率": "incre_rate_public_budget_revenue",
    "人均一般公共预算收入": "avg_public_budget_revenue",
    "城镇居民人均可支配收入": "city_avg_income",
    "城镇居民家庭人均可支配收入": "city_avg_income",
    "农村居民人均可支配收入": "country_avg_income",
    "农民居民人均纯收入": "country_avg_income",
    "农村居民家庭人均纯收入": "country_avg_income",
}

AREA_INDIMAP_UNIT = {
    "long_term_pop": {"unit": "万人", "name_zh": "常住人口"},
    "registered_pop": {"unit": "万人", "name_zh": "户籍人口"},
    "gdp": {"unit": "亿元", "name_zh": "GDP"},
    "avg_gdp": {"unit": "元", "name_zh": "人均GDP"},
    "incre_rate_gdp": {"unit": "%", "name_zh": "GDP增长率"},
    "public_budget_revenue": {"unit": "亿元", "name_zh": "一般公共预算收入"},
    "incre_rate_public_budget_revenue": {"unit": "%", "name_zh": "一般公共预算收入增长率"},
    "avg_public_budget_revenue": {"unit": "元", "name_zh": "人均一般公共预算收入"},
    "city_avg_income": {"unit": "元", "name_zh": "城镇居民人均可支配收入"},
    "country_avg_income": {"unit": "元", "name_zh": "农村居民人均可支配收入"},
}

# 合并计算型指标（去备注）到地市映射，供查询可选与自动计算入库
def _merge_calc_indicator_maps() -> None:
    try:
        from apps.coredata.calc_indicators import (
            get_calc_indimap_entries,
            get_calc_indimap_unit_entries,
        )
    except Exception:
        return
    for zh, en in get_calc_indimap_entries().items():
        INDIMAP.setdefault(zh, en)
    for en, meta in get_calc_indimap_unit_entries().items():
        INDIMAP_UNIT.setdefault(en, dict(meta))
    # 录入依赖补充
    INDIMAP.setdefault("受理信访举报案件数", "complaint_case_num")
    INDIMAP.setdefault("年末私营企业数", "private_company_year_end")
    INDIMAP_UNIT.setdefault(
        "complaint_case_num", {"unit": "件", "name_zh": "受理信访举报案件数"}
    )
    INDIMAP_UNIT.setdefault(
        "private_company_year_end", {"unit": "户（个）", "name_zh": "年末私营企业数"}
    )


_merge_calc_indicator_maps()
