"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = ['*']


CSRF_TRUSTED_ORIGINS = [
    # HTTPS 地址（现在主要使用这些）
    'https://www.city-index.cn',
    'https://city-index.cn',
    
    # HTTP 地址（重定向期间可能短暂使用，可以保留）
    'http://www.city-index.cn',
    'http://city-index.cn',
    
    # 本地测试地址（如果不需要可以删除）
    'http://8.140.225.109:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'tailwind',
    'django_htmx',
    'crispy_forms',
    'crispy_tailwind',
    'captcha', #图形验证码
    
    # Local apps
    'apps.accounts',
    'apps.landing',
    'apps.dashboard',
    'apps.subscriptions',
    'apps.coredata',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.system_admin',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎[citation:1][citation:3]
        'NAME': 'government_index',          # 你的数据库名[citation:1][citation:3]
        'USER': 'root',         # 你的MySQL用户名[citation:1][citation:3]
        'PASSWORD': 'Qhl718910!',     # 你的MySQL密码[citation:1][citation:3]
        'HOST': '127.0.0.1',                  # 数据库主机地址（本地为127.0.0.1）[citation:1][citation:3]
        'PORT': '3306',                       # 数据库端口（MySQL默认为3306）[citation:1][citation:3]
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

USE_TZ = True
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tailwind configuration
TAILWIND_APP_NAME = 'theme'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'tailwind'
CRISPY_TEMPLATE_PACK = 'tailwind'


# Django Allauth configuration注册登陆的配置
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'none' 

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_UNIQUE_EMAIL = True



# 设置allauth使用自定义表单（重要）
ACCOUNT_FORMS = {
    'signup': 'apps.accounts.forms.CustomSignupForm',  # 注意是 apps.accounts
}

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'


# 可选：设置缓存后端（用于存储验证码）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Login/Logout URLs
LOGIN_REDIRECT_URL = '/dashboard'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'account_login'

# 支付宝电脑网站支付（alipay.trade.page.pay）
# 开放平台需签约「电脑网站支付」
# ALIPAY_SIGN_MODE=key  → 公钥模式（应用私钥 + 支付宝公钥）
# ALIPAY_SIGN_MODE=cert → 公钥证书模式（应用私钥 + 三份证书）
# 未配置时：若存在 ALIPAY_PUBLIC_KEY_PATH 文件则自动用 key
ALIPAY_APP_ID = os.getenv('ALIPAY_APP_ID', 'mock_sandbox_app_id')
ALIPAY_SIGN_MODE = os.getenv('ALIPAY_SIGN_MODE', '')
ALIPAY_PRIVATE_KEY = os.getenv('ALIPAY_PRIVATE_KEY', '')
ALIPAY_PRIVATE_KEY_PATH = os.getenv('ALIPAY_PRIVATE_KEY_PATH', 'certs/alipay/app_private_key.pem')
ALIPAY_PRIVATE_KEY_PASSWORD = os.getenv('ALIPAY_PRIVATE_KEY_PASSWORD', '')
ALIPAY_PUBLIC_KEY = os.getenv('ALIPAY_PUBLIC_KEY', '')
ALIPAY_PUBLIC_KEY_PATH = os.getenv('ALIPAY_PUBLIC_KEY_PATH', 'certs/alipay/alipay_public_key.pem')
ALIPAY_APP_CERT = os.getenv('ALIPAY_APP_CERT', '')
ALIPAY_APP_CERT_PATH = os.getenv('ALIPAY_APP_CERT_PATH', 'certs/alipay/appCertPublicKey.crt')
ALIPAY_PUBLIC_CERT = os.getenv('ALIPAY_PUBLIC_CERT', '')
ALIPAY_PUBLIC_CERT_PATH = os.getenv('ALIPAY_PUBLIC_CERT_PATH', 'certs/alipay/alipayCertPublicKey_RSA2.crt')
ALIPAY_ROOT_CERT = os.getenv('ALIPAY_ROOT_CERT', '')
ALIPAY_ROOT_CERT_PATH = os.getenv('ALIPAY_ROOT_CERT_PATH', 'certs/alipay/alipayRootCert.crt')
ALIPAY_SANDBOX = os.getenv('ALIPAY_SANDBOX', 'true').lower() == 'true'
ALIPAY_MOCK = os.getenv('ALIPAY_MOCK', 'true').lower() == 'true'
ALIPAY_NOTIFY_URL = os.getenv(
    'ALIPAY_NOTIFY_URL',
    'https://city-index.cn/dashboard/api/alipay/notify/',
)
ALIPAY_RETURN_URL = os.getenv(
    'ALIPAY_RETURN_URL',
    'https://city-index.cn/landing/pricing/?pay=return',
)
ORDER_PAY_TIMEOUT_MINUTES = int(os.getenv('ORDER_PAY_TIMEOUT_MINUTES', '30'))

# 微信支付 Native（扫码）
# 商户平台 https://pay.weixin.qq.com 开通「Native支付」
WECHAT_APP_ID = os.getenv('WECHAT_APP_ID', '')
WECHAT_MCH_ID = os.getenv('WECHAT_MCH_ID', '')
WECHAT_API_V3_KEY = os.getenv('WECHAT_API_V3_KEY', '')
WECHAT_CERT_SERIAL_NO = os.getenv('WECHAT_CERT_SERIAL_NO', '')
WECHAT_PRIVATE_KEY = os.getenv('WECHAT_PRIVATE_KEY', '')
WECHAT_PRIVATE_KEY_PATH = os.getenv('WECHAT_PRIVATE_KEY_PATH', 'certs/wechat/apiclient_key.pem')
WECHAT_CERT_DIR = os.getenv('WECHAT_CERT_DIR', 'certs/wechat')
WECHAT_MOCK = os.getenv('WECHAT_MOCK', 'true').lower() == 'true'
WECHAT_NOTIFY_URL = os.getenv(
    'WECHAT_NOTIFY_URL',
    'https://city-index.cn/dashboard/api/wechat/notify/',
)

# 企查查企业二要素核验（ApiCode 855）
# 开放平台 https://openapi.qcc.com/dataApi/855
QICHACHA_APP_KEY = os.getenv('QICHACHA_APP_KEY', '')
QICHACHA_SECRET_KEY = os.getenv('QICHACHA_SECRET_KEY', '')
# true=未配置密钥时使用 Mock（信用代码以 MOCK 开头视为通过）
QICHACHA_MOCK = os.getenv('QICHACHA_MOCK', 'true').lower() == 'true'

# Stripe settings
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_ID = os.getenv('STRIPE_PRICE_ID', '')

# 日志目录（勿覆盖上方项目 BASE_DIR，否则相对路径如证书会解析错）
LOG_DIR = os.getenv('LOG_DIR', '/var/log/gov/logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # 控制台输出
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 调试日志文件
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # 错误日志文件
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Django请求日志
        'request_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'request.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'debug_file', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['request_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['request_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {  # 你的应用日志
            'handlers': ['console', 'debug_file'],
            'level': 'DEBUG',
        },
    },
}
