# Generated by Django 4.2.27 on 2025-12-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompositeScoreFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("version", models.CharField(default="v1", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config_json",
                    models.JSONField(
                        help_text="保存权重、参与指标等配置，具体格式你自己约定"
                    ),
                ),
            ],
            options={
                "verbose_name": "综合绩效公式",
                "verbose_name_plural": "综合绩效公式",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[("input", "录入指标"), ("computed", "计算指标")],
                        default="input",
                        max_length=16,
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="指标分类，比如经济、社会、环境等",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "指标",
                "verbose_name_plural": "指标",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "省份",
                "verbose_name_plural": "省份",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ComputedIndicatorRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="公式表达式（可自定义语法 或 JSON 配置）"
                    ),
                ),
                (
                    "indicator",
                    models.OneToOneField(
                        help_text="该规则对应的计算型指标",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compute_rule",
                        to="coredata.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "计算指标规则",
                "verbose_name_plural": "计算指标规则",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="coredata.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市",
                "ordering": ["province__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="CityIndicatorValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="manual", max_length=32),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="coredata.city",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_values",
                        to="coredata.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "城市指标值",
                "verbose_name_plural": "城市指标值",
                "indexes": [
                    models.Index(
                        fields=["city", "year"], name="coredata_ci_city_id_cf5228_idx"
                    ),
                    models.Index(
                        fields=["indicator", "year"],
                        name="coredata_ci_indicat_ee38c9_idx",
                    ),
                ],
                "unique_together": {("city", "year", "indicator")},
            },
        ),
    ]
