# Generated by Django 6.0 on 2026-01-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeScoreFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.JSONField(help_text='保存权重、参与指标等配置，具体格式你自己约定')),
            ],
            options={
                'verbose_name': '综合绩效公式',
                'verbose_name_plural': '综合绩效公式',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=2026, help_text='请输入四位数的年份', null=True, verbose_name='指标年份')),
                ('province_id', models.IntegerField(default=0, help_text='指标的省id', verbose_name='省id')),
                ('city_id', models.IntegerField(default=0, help_text='如：110000（北京市代码）', verbose_name='城市id')),
                ('source', models.CharField(default='未知来源', help_text='指标数据来源名称或机构', max_length=50, verbose_name='数据来源')),
                ('value', models.DecimalField(decimal_places=2, default='', help_text='指标的数值', max_digits=10, verbose_name='数值')),
                ('name_en', models.CharField(help_text='指标英文名/代码，如: pm25, gdp_per_capita', max_length=50, unique=True, verbose_name='英文名')),
                ('name_zh', models.CharField(help_text='指标中文名，如：人均GDP，PM2.5浓度', max_length=50, verbose_name='中文名')),
                ('input_form', models.CharField(choices=[('INPUT', '录入型'), ('CALC', '计算型')], help_text='录入型：人工/系统直接录入；计算型：由公式或模型计算', max_length=16, verbose_name='指标输入形式')),
                ('indicator_type', models.CharField(choices=[('ENV', '环境'), ('JUD', '司法'), ('ECO', '经济'), ('SOC', '社会'), ('GOV', '治理'), ('OTH', '其他')], help_text='如：环境、司法、经济、社会、治理等', max_length=8, verbose_name='指标类型')),
            ],
            options={
                'verbose_name': '指标',
                'verbose_name_plural': '指标',
                'ordering': ['indicator_type', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ComputedIndicatorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(help_text='公式表达式（可自定义语法 或 JSON 配置）')),
                ('indicator', models.OneToOneField(help_text='该规则对应的计算型指标', on_delete=django.db.models.deletion.CASCADE, related_name='compute_rule', to='coredata.indicator')),
            ],
            options={
                'verbose_name': '计算指标规则',
                'verbose_name_plural': '计算指标规则',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='coredata.province')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['province__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CityRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('source_type', models.CharField(blank=True, default='manual', max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_city', to='coredata.city')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_values', to='coredata.indicator')),
            ],
            options={
                'verbose_name': '城市指标值',
                'verbose_name_plural': '城市指标值',
                'indexes': [models.Index(fields=['city', 'year'], name='coredata_ci_city_id_a9d40a_idx'), models.Index(fields=['indicator', 'year'], name='coredata_ci_indicat_580372_idx')],
                'unique_together': {('city', 'year', 'indicator')},
            },
        ),
    ]
