# Generated by Django 6.0 on 2026-01-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='note',
            field=models.CharField(blank=True, help_text='指标备注信息', max_length=50, verbose_name='备注'),
        ),
    ]
