# Generated by Django 4.2.27 on 2025-12-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coredata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicator",
            options={
                "ordering": ["indicator_type", "name_en"],
                "verbose_name": "指标",
                "verbose_name_plural": "指标",
            },
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="category",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="code",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="description",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="name",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="type",
        ),
        migrations.RemoveField(
            model_name="indicator",
            name="unit",
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_type",
            field=models.CharField(
                choices=[
                    ("ENV", "环境"),
                    ("JUD", "司法"),
                    ("ECO", "经济"),
                    ("SOC", "社会"),
                    ("GOV", "治理"),
                    ("OTH", "其他"),
                ],
                default="-",
                help_text="如：环境、司法、经济、社会、治理等",
                max_length=8,
                verbose_name="指标类型",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indicator",
            name="input_form",
            field=models.CharField(
                choices=[("INPUT", "录入型"), ("CALC", "计算型")],
                default="-",
                help_text="录入型：人工/系统直接录入；计算型：由公式或模型计算",
                max_length=16,
                verbose_name="指标输入形式",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indicator",
            name="name_en",
            field=models.CharField(
                default="-",
                help_text="指标英文名/代码，如: pm25, gdp_per_capita",
                max_length=128,
                unique=True,
                verbose_name="英文名",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indicator",
            name="name_zh",
            field=models.CharField(
                default="-",
                help_text="指标中文名，如：人均GDP，PM2.5浓度",
                max_length=128,
                verbose_name="中文名",
            ),
            preserve_default=False,
        ),
    ]
