# Generated by Django 4.2.27 on 2025-12-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coredata", "0002_alter_indicator_options_remove_indicator_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="manual", max_length=32),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "城市指标值",
                "verbose_name_plural": "城市指标值",
            },
        ),
        migrations.AlterModelOptions(
            name="cityindicatorvalue",
            options={
                "ordering": ["-year", "city"],
                "verbose_name": "城市指标值",
                "verbose_name_plural": "城市指标值",
            },
        ),
        migrations.RemoveIndex(
            model_name="cityindicatorvalue",
            name="coredata_ci_city_id_cf5228_idx",
        ),
        migrations.RemoveIndex(
            model_name="cityindicatorvalue",
            name="coredata_ci_indicat_ee38c9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="cityindicatorvalue",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="last_year_value",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="city_indicator_values",
                to="coredata.province",
                verbose_name="省份",
            ),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CITY_STAT_YB", "地市统计年鉴"),
                    ("CITY_YB", "地市年鉴"),
                    ("CITY_DEV_BUL", "地市级发展公报"),
                    ("CITY_GOV_RPT", "地市级政府工作报告"),
                    ("PROV_STAT_YB", "省级统计年鉴"),
                    ("PROV_YB", "省级年鉴"),
                    ("PROF_YB", "专业年鉴"),
                    ("SPECIAL_RPT", "专项报告"),
                    ("GOV_INFO_RPT", "政府信息公开报告"),
                ],
                max_length=32,
                null=True,
                verbose_name="指标来源",
            ),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="cityindicatorvalue",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_city_indicator_values",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cityindicatorvalue",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indicator_values",
                to="coredata.city",
                verbose_name="城市",
            ),
        ),
        migrations.AlterField(
            model_name="cityindicatorvalue",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="city_values",
                to="coredata.indicator",
                verbose_name="指标",
            ),
        ),
        migrations.AlterField(
            model_name="cityindicatorvalue",
            name="value",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=20,
                null=True,
                verbose_name="数值",
            ),
        ),
        migrations.AlterField(
            model_name="cityindicatorvalue",
            name="year",
            field=models.PositiveIntegerField(verbose_name="年份"),
        ),
        migrations.AlterUniqueTogether(
            name="cityindicatorvalue",
            unique_together={("year", "city", "indicator")},
        ),
        migrations.AddField(
            model_name="cityrank",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_city",
                to="coredata.city",
            ),
        ),
        migrations.AddField(
            model_name="cityrank",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_values",
                to="coredata.indicator",
            ),
        ),
        migrations.RemoveField(
            model_name="cityindicatorvalue",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="cityindicatorvalue",
            name="source_type",
        ),
        migrations.AddIndex(
            model_name="cityrank",
            index=models.Index(
                fields=["city", "year"], name="coredata_ci_city_id_a9d40a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cityrank",
            index=models.Index(
                fields=["indicator", "year"], name="coredata_ci_indicat_580372_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cityrank",
            unique_together={("city", "year", "indicator")},
        ),
    ]
