# Generated by Django 6.0 on 2026-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0002_indicator_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(help_text='指标英文名/代码，如: pm25, gdp_per_capita', max_length=50, verbose_name='英文名'),
        ),
    ]
