# Generated by Django 6.0 on 2026-01-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0003_alter_indicator_name_en'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('year', 'city_id', 'name_en')},
        ),
    ]
