# Generated by Django 6.0 on 2026-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_alter_indicator_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=2026, help_text='请输入四位数的年份', null=True, verbose_name='指标年份')),
                ('province_id', models.IntegerField(default=0, help_text='指标的省id', verbose_name='省id')),
                ('city_id', models.IntegerField(default=0, help_text='如：110000（北京市代码）', verbose_name='城市id')),
                ('area', models.CharField(default='未知区县', help_text='指标的区县名称或ID', max_length=50, verbose_name='区县')),
                ('source', models.CharField(default='未知来源', help_text='指标数据来源名称或机构', max_length=50, verbose_name='数据来源')),
                ('value', models.DecimalField(decimal_places=2, default='', help_text='指标的数值', max_digits=10, verbose_name='数值')),
                ('name_en', models.CharField(help_text='指标英文名/代码，如: pm25, gdp_per_capita', max_length=50, verbose_name='英文名')),
                ('name_zh', models.CharField(help_text='指标中文名，如：人均GDP，PM2.5浓度', max_length=50, verbose_name='中文名')),
                ('note', models.CharField(blank=True, help_text='指标备注信息', max_length=50, verbose_name='备注')),
                ('input_form', models.CharField(choices=[('INPUT', '录入型'), ('CALC', '计算型')], help_text='录入型：人工/系统直接录入；计算型：由公式或模型计算', max_length=16, verbose_name='指标输入形式')),
                ('indicator_type', models.CharField(choices=[('ENV', '环境'), ('JUD', '司法'), ('ECO', '经济'), ('SOC', '社会'), ('GOV', '治理'), ('OTH', '其他')], help_text='如：环境、司法、经济、社会、治理等', max_length=8, verbose_name='指标类型')),
            ],
            options={
                'verbose_name': '指标',
                'verbose_name_plural': '指标',
                'ordering': ['indicator_type', 'name_en'],
                'unique_together': {('year', 'city_id', 'name_en')},
            },
        ),
    ]
