# Generated by Django 6.0 on 2026-03-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_indicatorarea'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorarea',
            unique_together={('year', 'city_id', 'name_en', 'area')},
        ),
    ]
