# Generated by Django 6.0 on 2026-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0006_alter_indicatorarea_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationMultiplierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_code', models.CharField(choices=[('year', '年卡'), ('month', '月卡'), ('week', '周卡')], db_index=True, max_length=20, unique=True, verbose_name='时长代码')),
                ('duration_name', models.CharField(max_length=20, verbose_name='时长显示名')),
                ('multiplier', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='系数值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '时长系数配置',
                'verbose_name_plural': '时长系数配置',
                'db_table': 'duration_multiplier_config',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('personal', '个人用户'), ('org', '机构用户')], db_index=True, max_length=20, verbose_name='用户类型')),
                ('user_type_name', models.CharField(max_length=50, verbose_name='用户类型显示名')),
                ('indicator_name', models.CharField(max_length=200, verbose_name='指标名称')),
                ('indicator_desc', models.CharField(blank=True, default='', max_length=500, verbose_name='指标描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '指标配置',
                'verbose_name_plural': '指标配置',
                'db_table': 'indicator_config',
                'ordering': ['user_type', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['user_type', 'is_active'], name='idx_user_type_active')],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='全国/地区/省/直辖市/市', max_length=50, verbose_name='权限级别')),
                ('level_code', models.CharField(choices=[('national', '全国'), ('region', '地区'), ('province', '省'), ('municipality', '直辖市'), ('city', '市')], db_index=True, max_length=50, verbose_name='级别代码')),
                ('user_type', models.CharField(choices=[('personal', '个人用户'), ('org', '机构用户')], db_index=True, max_length=20, verbose_name='用户类型')),
                ('user_type_name', models.CharField(max_length=50, verbose_name='用户类型显示名')),
                ('duration', models.CharField(choices=[('year', '年'), ('month', '月'), ('week', '周'), ('15days', '15天'), ('24hour', '24小时')], db_index=True, max_length=20, verbose_name='时长')),
                ('duration_name', models.CharField(max_length=20, verbose_name='时长显示名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格（元）')),
                ('days', models.IntegerField(verbose_name='对应天数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '价格配置',
                'verbose_name_plural': '价格配置',
                'db_table': 'pricing_config',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['level_code', 'user_type', 'duration'], name='idx_level_user_duration')],
            },
        ),
    ]
